### ISSUE TITLE
Deploy Grafana Operator for KLAB Cluster

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#1059]
**Describe the issue**
Deploy grafana for OCP4 clusters using [Grafana Operator](https://github.com/integr8ly/grafana-operator/tree/v3.9.0/documentation), and create OCP4 cluster dashboard as we are doing in OCP3 cluster. 

**Additional context**
OCP3: https://github.com/bcgov-c/platform-ops/blob/master/tools/openshift-monitoring/grafana-public.yaml
OCP4 example : https://www.redhat.com/en/blog/custom-grafana-dashboards-red-hat-openshift-container-platform-4
OCP4 implementing OAuth example:  https://github.com/integr8ly/grafana-operator/blob/master/deploy/examples/oauth/Grafana.yaml
OAuth example: https://www.openshift.com/blog/thanos-querier-versus-thanos-querier
How to get SA Token using CCM: https://gexperts.com/wp/openshift-user-application-monitoring-and-grafana-the-gitops-way/

**Definition of done**
- [x] Install Grafana Operator in KLAB
- [x] Set up Grafana-Prometheus integration in KLAB
- [x] Set up OAuth for Grafana-Prometheus integration in KLAB
- [x] Documentation in GitHUB

**Comment by tmorik** [comment]
Installed Grafana Operator in KLAB under `advsol-grafana` namespace.

**Comment by tmorik** [comment]
Testing KLAB Grafana has been set up using basic authorization. 

Sample dashborads: 
  - [KLAB Cluster Status](https://grafana-route-advsol-grafana.apps.klab.devops.gov.bc.ca/d/OE4czEwGk/klab-cluster-status?orgId=1&from=1616692705186&to=1616714305186)
  - [KLAB HAPROXY & Router Pods Status](https://grafana-route-advsol-grafana.apps.klab.devops.gov.bc.ca/d/ppLuryQMz/klab-haproxy-and-router-pods-status?orgId=1&from=1616684368830&to=1616686058216)

**Comment by tmorik** [comment]
Re-install Grafana Operator in KLAB with OAuth settings.

**Comment by StevenBarre** [comment]
Can we change the namespace to `openshift-bcgov-grafana` when you have time?

Is it possible to define dashboards with the GrafanaDashboard custom resource? any tips on how to do that once you've designed a dashboard you like?

**Comment by tmorik** [comment]
Hmmm looks like cannot use "openshift-" prefix ? 

```
[root@mcs-klab-util ~]# oc new-project openshift-bcgov-grafana
Error from server (Forbidden): project.project.openshift.io "openshift-bcgov-grafana" is forbidden: cannot request a project starting with "openshift-"
[root@mcs-klab-util ~]#
```

**Comment by tmorik** [comment]
namespace `openshift-bcgov-grafana`
```
[root@mcs-klab-util ~]# oc create namespace openshift-bcgov-grafana
namespace/openshift-bcgov-grafana created
```

I will use this namespace, once Oauth issue is resolved.

**Comment by tmorik** [comment]
namespace `openshift-bcgov-grafana-test` for testing has been created and Grafana Operator installed. grafana-test website launched with OAuth :  https://grafana-route-openshift-bcgov-grafana-test.apps.klab.devops.gov.bc.ca/?orgId=1

Next step is to figure out how to assign grafana role to the authenticated users. Currently users will be assigned as "Viewer", we need to assign as "Editor" or "Admin".

**Comment by tmorik** [comment]
It seems that if a deployed grafana.yaml has the "[users]" configuraiton in it, it will crush and won't run properly.

 In the OCP 3's grafana is using `auto_assign_org_role = Admin` config in the [users] to give OAuthed user to have admin permission within the grafana. However, the same setting in the OCP4.5's Grafana Operator won't give you the Admin... 

This won't work cannot create grafana if it's first time. Or apply won't change anything.:
```yaml
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-oauth
  namespace: openshift-bcgov-grafana-test
spec:
  config:
    auth:
      disable_login_form: true
      disable_signout_menu: true
      oauth_auto_login: true
    auth.anonymous:
      enabled: false
    auth.basic:
      enabled: false
    auth.proxy:
      auto_sign_up: true
      enabled: true
      header_name: X-Forwarded-User
      header_property: username
      auto_sign_up: true
    users:
      allow_sign_up: true
      allow_org_create: true
      auto_assign_org: true
      auto_assign_org_id: 1
      auto_assign_org_role: Editor
<...>
```

This will work but all users will be a View user, unless grafana's local root user give you the permission.
```yaml
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-oauth
  namespace: openshift-bcgov-grafana-lab
spec:
  config:
    auth:
      disable_login_form: true
      disable_signout_menu: true
      oauth_auto_login: true
    auth.anonymous:
      enabled: true
    auth.basic:
      enabled: true
    auth.proxy:
      auto_sign_up: true
      enabled: true
      header_name: X-Forwarded-User
      header_property: username
```

At this point,  For controling user permission, keep the local root user in grafana, and give a permission to users if they need to add/change/delete the graphs, otherwise they will be stay as View (read only) users.
