### ISSUE TITLE
Change Artifactory docker repo routes

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#1137]
**Describe the issue**
Artifactory docker routes for container repos (whether caching repos or private repos) currently uses subdomain paths.  This creates additional management overhead in the forms of:
- Creating a route manifest for every docker repository in artifactory
- Managing a wildcard subdomain certificate for `*.artifacts.developer.gov.bc.ca`
- Additional complexity for all private repo secrets (each secret has to have the URL of all artifactory repositories included in the secret)
- Provisioning Operators on multiple clusters are unable to provision routes in the artifactory service to match. (blocker for multi-cluster Archeobot)

**Additional context**
- Testing was successful in validating that performance was comparable between subdomain based routes and path based routes. (see #949)
- path based docker routes is not supported for dockerV1 clients (OCP 3 and 4 both support docker v2 registry APIs)

**Definition of done**
- [x] Configure lab artifactory service to use path-based container registry URLs
- [x] Configure Caddy (NGINX?) service to forward existing subdomain routes to appropriate path-based routes.
- [x] Redirect subdomain route manifests to new Caddy forwarding service
- [x] Validate subdomain docker push/pull actions through new forwarding service
- [x] Repeat for Production service.

**Comment by jleach** [comment]
The Caddy proxy works now with the artifactory installation in klab. Both `docker pull` and a deployment are working with it. Next step is some more testing then planning to cut over the route on Silver (probably one at at time) to use the proxy and redirect to the new URL.

**Comment by jleach** [comment]
Added (PR)[https://github.com/BCDevOps/developer-experience/pull/1289] with manifest and docs.

**Comment by jleach** [comment]
Deployed to Production 🎉

We rolled out the change at 12PM today. No issues. Took about 3 min.

Changes include:

1. Deploying the proxy earlier in the day as prep.
2. Cailey updated Artifactory.
3. Jason updated the `docker-remote` and `redhat-docker-remote` routes YAML as follows:

**before**

```yaml
spec:
  host: redhat-docker-remote.artifacts.developer.gov.bc.ca
  to:
    kind: Service
    name: artifactory-ha
    weight: 100
  port:
    targetPort: artifactory
```

**after**

```yaml
spec:
  host: redhat-docker-remote.artifacts.developer.gov.bc.ca
  to:
    kind: Service
    name: proxy
    weight: 100
  port:
    targetPort: 2015-tcp
```
