### ISSUE TITLE
SealedSecrets Continuous Reconcile Issue - SPIKE

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1364]
**Problem & Investigation**

The team integrated Gold Calgary into CCM on Tuesday / Wednesday. We noticed all of the Sealed Secrets resources were continuously syncing in ArgoCD. (Many many API calls) The sealed secrets controller was identified as continuously reconciling and was restarted but with no effect. Automated Sync (self healing) was disabled on the ArgoCD Applications and the sealed secrets controller continued reconciling the same objects infinitely. This ruled out ArgoCD as the cause. 

We then compared the sealed secrets manifests in Gold Kamloops and Kamloops Lab with Gold Calgary. Everything was identical. Individual SealedSecrets objects were compared next and this showed the problem was that the status was not being set for the Sealed Secrets Custom Resource Objects on Gold Calgary. A comparison of the Sealed Secrets Custom Resource Definition showed that the applied manifest had been modified on apply.

KLAB: OCP 4.6.25
GOLD: OCP 4.6.25
```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: sealedsecrets.bitnami.com
  labels:
    app: sealed-secrets
spec:
  group: bitnami.com
  names:
    plural: sealedsecrets
    singular: sealedsecret
    kind: SealedSecret
    listKind: SealedSecretList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  conversion:
    strategy: None
## preseveUnknownFields: true is not set on the Gold Calgary Cluster
## The following line is injected ... no longer a valid setting or injection in 4.6.32
  preserveUnknownFields: true
```

A Possible Solution:
GOLDR: OCP 4.6.32
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
spec:
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
#### The next two lines need to be added
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
```

It works! :tada:

Definition of Done:
- [x] Sealed Secrets CCM Role updated with fix
- [x] Tested on 4.6.25 and 4.6.32
- [ ] Rolled out to all clusters
