### ISSUE TITLE
Add service quota to all namespaces

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1911]
**Describe the issue**

The F5 CIS operator generates ERROR logs due to the presence of LoadBalancer type service objects. Some investigation shows some teams also have NodePort services. Neither of these are supported in our cluster. Teams should instead use ClusterIP type for their services.

We can set a quota of zero for both NodePort and LoadBalancer services in all customer namespaces via the Project Registry to prevent their use.

**Additional context**

https://kubernetes.io/docs/concepts/policy/resource-quotas/

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    services.loadbalancers: "0"
    services.nodeports: "0"
```

**Definition of done**

- [x] PR to add the new quota to all namespaces
- [ ] Plan the date for it to be applied as we need to ensure all the dev teams are ready and its been properly announced
- [ ] Apply the new quotas to all namespaces
