### ISSUE TITLE
Autocreated netpols from Kafka operator don't work | SPIKE

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2458]
**Describe the issue**
As part of the RH Integration tools installed for AG, the Kafka CR creates a Zookeeper and Kafka statefulset and assiciated network policies. However the operator pod appears to be unable to connect to the STS.

The operator generated netpol contains

```yaml
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          strimzi.io/kind: cluster-operator
```

which should match the operator pod in the `openshift-operator` namespace, but seem to not be.

This is working fine in CLAB, but not in SILVER.

**Additional context**
https://access.redhat.com/support/cases/#/case/03174750

Workaround netpols
```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-zookeeper
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-operators
      podSelector:
        matchLabels:
          strimzi.io/kind: cluster-operator
    ports:
    - port: 2181
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: events-zookeeper
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-kafka
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-operators
      podSelector:
        matchLabels:
          strimzi.io/kind: cluster-operator
    ports:
    - port: 9091
      protocol: TCP
  - ports:
    - port: 9092
      protocol: TCP
  - ports:
    - port: 9093
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: events-kafka
  policyTypes:
  - Ingress
```

**Definition of done**
- Creating a Kafka object spins up all needed pods without need of a workaround netpol
