### ISSUE TITLE
SPIKE | NCP-Bootstrap pods crashloop when adding additional packages to CoreOS

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2718]
**Describe the issue**
In our openshift deployment, we run sysdig agents.

The ability to run this agent requires the kernel-devel package installed on the nodes to build its kernel module.

We normally do this by updating the Machine Config.

```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 05-worker-advsol
spec:
  extensions:
    - kernel-devel
```

We have no problems doing this process on non NSXT / NCP OpenShift VMware clusters.
When the process runs CoreOS installs this package from yum and leaves some artifacts in `/var/lib/yum`.

The nsx-ncp-bootstrap pods also do somethings via yum, and then try to clear the yum cache. But by then CoreOS has mounted that filesystem as read-only and the NSX-Bootstrap pod fails to start.

We’ve worked around this for now by removing the machine config to install that package, so the yum folder is empty. But we will need to get it working to allow installing the Sysdig agent.

**Additional context**
VMware Case: 22334428206

**Definition of done**
Both Sysdig agent pods and nsx-bootstrap pods are running happily
