### ISSUE TITLE
Connect Legacy DC NFS servers to pods

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2849]
**Describe the issue**
AG has some NFS servers in the legacy DC they want to connect to from pods. We've done a proof of concept already to show the NFS can be mounted. Now we need to decide if we'll operationalize this or not.

**Additional context**
Create a matching PV/PVC to enable
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adobecommonservice-nfs-pvc-poc
  namespace: license-dev
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi #Irrelevant value
  volumeName: test-nfs-license
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-nfs-license
spec:
  storageClassName: ""
  claimRef:
    name: adobecommonservice-nfs-pvc-poc
    namespace: license-dev
  capacity: 
    storage: 1Gi #Irrelevant value
  accessModes:
    - ReadWriteMany
  nfs:
    server: 1.2.3.4
    readOnly: false
    path: "/data/exports"
```

**How does this benefit the users of our platform?**
Allow AG to access existing mass storage without creating an API interface to act in the middle.

**Definition of done**
- [x] confirm technical viability
  - [x] test the scenario of firewall maint dropping NFS connections in a LAB cluster
- [x] confirm that this is a supportable feature of the MCS platform; that this Sector will see at least 2 apps use it right away, and others could shift off existing approach of  SFTP-client and/or large-payload single-chunk API/HTTP request/response
- [ ] develop operational support procedure, including how this kind of resource is requested
