### ISSUE TITLE
ArgoCD notification for ACS syn (rhacs)

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2857]
**Describe the issue**
There have been problem with the argocd syncing of ACS (application 'rhacs').  Enable RocketChat alerts for failed syncs, but not for the "missing install plan" error.

**How does this benefit the users of our platform?**

**Definition of done**
- [ ] test on setup
- [ ] add alerts for shared services

**Comment by ShellyXueHan** [comment]
### A Note about ACS operator subscription status issue with ArgoCD:

From time to time we got `InstallPlanMissing` status from ACS operator sub and ArgoCD consider it as a sync failure, which is a [known issue](https://issues.redhat.com/browse/GITOPS-2018).

Here's the status from the sub:
```
  conditions:
  - lastTransitionTime: "2022-06-06T16:47:50Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  - lastTransitionTime: "2022-07-13T16:37:23Z"
    reason: ReferencedInstallPlanNotFound
    status: "True"
    type: InstallPlanMissing
  - message: 'constraints not satisfiable: @existing/openshift-operators//openshift-pipelines-operator-rh.v1.7.2
      and @existing/openshift-operators//openshift-pipelines-operator-rh.v1.7.1 originate
      from package openshift-pipelines-operator-rh, clusterserviceversion openshift-pipelines-operator-rh.v1.7.1
      exists and is not referenced by a subscription, subscription openshift-pipelines-operator
      requires @existing/openshift-operators//openshift-pipelines-operator-rh.v1.7.2,
      subscription openshift-pipelines-operator exists'
    reason: ConstraintsNotSatisfiable
    status: "True"
    type: ResolutionFailed
  currentCSV: rhacs-operator.v3.70.1
  installPlanGeneration: 31
```

This would be an issue if we want to setup notification from ArgoCD.

Before ArgoCD or OpenShift GitOps include this fix, we would consider Gerald's solution to it: https://github.com/gnunn-gitops/gitops-operator-install/blob/main/openshift-gitops/base/openshift-gitops-cr.yaml#L66

@IanKWatts lmk your thoughts and if you'd like me to create a separate ticket for this!
