### ISSUE TITLE
Document how to add Prometheus instrumentation to an app

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2925]
**Describe the issue**
Convert my slide deck from the recent Community Meetup into a docs page in beta-docs

**Additional context**
See my [slide deck](https://advsolcan.sharepoint.com/:p:/r/sites/ManagedContainerServicesMCS/Shared%20Documents/Daily%20Ops/OCP%20Talks/2022--08-02%20User%20Defined%20Monitoring.pptx?d=w7be7783da8994b86bf37385fe61b0383&csf=1&web=1&e=NakSkC)

**How does this benefit the users of our platform?**
Demonstrate how to add instrumentation to apps for custom metrics

**Definition of done**
Page published on https://beta-docs.developer.gov.bc.ca/
- Instrument app
- Get metrics in OCP
- Get metrics in Sysdig

**Comment by tmorik** [comment]
Start drafting doc here: https://github.com/bcgov/platform-developer-docs/pull/145

**Comment by tmorik** [comment]
Checking `Get metrics in Sysdig`.

**Comment by tmorik** [comment]
Re: `Get metrics in Sysdig`, I will summarize [Sending StatsD Metrics](https://docs.sysdig.com/en/docs/sysdig-monitor/monitoring-integrations/custom-integrations/integrate-statsd-metrics/#sending-statsd-metrics) doc, which has been used for `statsd_MCS_XXXX` custom metrics in the Sysdig. -- It is collected by MCS's nagios monitoring and sent to Sysdig.

**Comment by StevenBarre** [comment]
@ShellyXueHan can you help with getting sysdig to scrape custom prometheus endpoints?

**Comment by tmorik** [comment]
Thanks to Steven, it looks like we just need to have an annotation below.

`prometheus.io/scrape=true`

Doc: https://docs.sysdig.com/en/docs/sysdig-monitor/monitoring-integrations/custom-integrations/collect-prometheus-metrics/#agent-compatibility

**Comment by tmorik** [comment]
.. and Sysdig agent has already the Prometheus setting in its configmap:

From the CCM's template `cm-sysdig-agent.yaml.j2`
```
<...>
    ### Prometheus
    # enable that the metrics being scrapped is mapped to the application container instead of sysdig agent container
    promscrape_fastproto: true
    prometheus:
      enabled: true
      prom_service_discovery: true
      interval: 30
      log_errors: true
      # max_metrics: 3000 (defualt set to 8000)
      histograms: false
```
