### ISSUE TITLE
Investigate how VPA will work for HA cluster apps, such as a patroni cluster? 

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#2987]
**Describe the issue**
Is the VPA smart enough to know how to use the resources of the primary and secondary pods, since the VPA has no control over who is the primary, and if it fails over, the statistics are messed up, but are they accurate?

**Additional context**
RC : https://chat.developer.gov.bc.ca/group/internal-platform-services?msg=jS34nebyYbtg79eWJ

**Definition of done**
- [x] Dig document
- [x] Test the scenario
- [x] Documenting
- [x] Send the doc and ask uploading the doc to govt doc site with "VPA", "HPA" tags.

**Comment by tmorik** [comment]
As long as a HA stateful workload such as patroni is being deplyed using StatefulSet, VPA will work. 
- [How to use VPA with database pod in kubernetes?](https://stackoverflow.com/questions/62888299/how-to-use-vpa-with-database-pod-in-kubernetes)
- [Correctly set up your deployment](https://cloud.google.com/blog/products/containers-kubernetes/best-practices-for-creating-a-highly-available-gke-cluster)

Will test a patroni cluster and VPA using [Patroni OpenShift Configuration Examples](https://github.com/zalando/patroni/tree/master/kubernetes/openshift-example.)

**Comment by tmorik** [comment]
## Testing summary
It seems that VPA is calculating its recommendations using `StatefulSet`'s cpu&memory configuration, which means that VPA's recommended values are for not each individual PODs but for all replicated PODs --> all pods will have the same cpu and memory capacity specs.   

Therefore, regardless of the patroni HA DB cluster's status (if it's failed over or not), VPA's calculation won't be impacted by that move. It's watching at `statefulset` status as a whole, but not each pods.

### Statefulset example

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2022-09-22T20:12:12Z"
  generation: 17
  labels:
    app: patroni
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: patroni
    app.kubernetes.io/managed-by: template
    app.kubernetes.io/name: patroni
    cluster-name: patroni
<...>
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
<...>
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 25m
            memory: 512Mi
<...>
```

### VPA example

```yaml
CLAB/tats-test ~ $ cat patroni-vpa-test.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: patroni-test-vpa
  namespace: tats-test
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       patroni
  updatePolicy:
    updateMode: "Off"
```

### VPA's recommendation example

```yaml
oc get vpa -o json | jq -r '.items[].status'

{
  "conditions": [
    {
      "lastTransitionTime": "2022-09-22T20:35:49Z",
      "status": "True",
      "type": "RecommendationProvided"
    }
  ],
  "recommendation": {
    "containerRecommendations": [
      {
        "containerName": "postgresql",
        "lowerBound": {
          "cpu": "62m",
          "memory": "262144k"
        },
        "target": {
          "cpu": "93m",
          "memory": "262144k"
        },
        "uncappedTarget": {
          "cpu": "93m",
          "memory": "262144k"
        },
        "upperBound": {
          "cpu": "628m",
          "memory": "1839133401"
        }
      }
    ]
  }
}

```

### Change VPA to `Auto` mode and observe pod status.

```console
oc get pods -o wide && oc get pods  -o custom-columns="NAME:.metadata.name, CPU_REQ:.spec.containers[*].resources.requests.cpu, MEM_REQ:.spec.containers[*].resources.requests.memory, CPU_LIM:.spec.containers[*].resources.limits.cpu, MEM_LIM:.spec.containers[*].resources.limits.memory " && echo "--" && oc get vpa

// Pods
NAME        READY   STATUS    RESTARTS   AGE    IP            NODE                  NOMINATED NODE   READINESS GATES
patroni-0   1/1     Running   0          104m   10.95.14.58   mcs-clab-app-04.dmz   <none>           <none>
patroni-1   1/1     Running   0          105m   10.95.10.61   mcs-clab-app-01.dmz   <none>           <none>
patroni-2   1/1     Running   0          106m   10.95.12.29   mcs-clab-app-03.dmz   <none>           <none>

// All three pods were updated based on VPA's recommendation (Target) 
NAME         CPU_REQ    MEM_REQ    CPU_LIM    MEM_LIM
patroni-0   93m        262144k    930m       262144k
patroni-1   93m        262144k    930m       262144k
patroni-2   93m        262144k    930m       262144k

// VPA recommendation summary 
NAME               MODE   CPU   MEM       PROVIDED   AGE
patroni-test-vpa   Auto   93m   262144k   True       3h59m
```
