### ISSUE TITLE
Set up monitoring of DHCP service on util servers

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3091]
**Describe the issue**
The DHCP service is critical to the functioning of the MCS clusters. It should be monitored to ensure nodes are able to get IP addresses.

**What is the Value/Impact?**
Ensure cluster stability

**What is the plan? How will this get completed?**
Extend the Nagios agent on the nodes to also check the status of dhcpd service.

**Identify any dependencies**
None

**Definition of done**
All util hosts have dhcpd service monitored

**Comment by StevenBarre** [comment]
```
LIMIT=$(date --date='+5 hour' '+%s');
for T in $(nmcli -f dhcp4.option dev show | sed -n -e '/expiry/s/.*expiry = //p');
do
  if (( "$T" < "$LIMIT" )); then
    echo "DHCP lease expiring in less than 5 hours";
    exit 1;
  fi;
done
```

**Comment by StevenBarre** [comment]
We likely need another set of pods in a DeamonSet that is privileged so it can run on all nodes and see the nodes network stack.

**Comment by tmorik** [comment]
To install nmcli in a container, tested a couple of images for nmcli, but so far only centos7 is successful. Tried `registry.redhat.io/openshift4/network-tools-rhel8`, but it looks like it could not find `NetworkManager` when it's been built. 

```yaml
//BuildConfig
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: dhcp-monitor-nmcli-nw-tools-rhel8
    namespace: openshift-bcgov-nagios # your namespace
spec:
  runPolicy: Serial
  source:
    dockerfile: |
      FROM registry.redhat.io/openshift4/network-tools-rhel8:latest
      # Install nmcli
      RUN yum install -y NetworkManager && yum clean all

  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
  output:
    to:
      kind: ImageStreamTag
      name: "dhcp-monitor-nmcli-nw-tools-rhel8:latest"
```
Logs during the build:
```
//Logs during the build
Defaulted container "docker-build" out of: docker-build, manage-dockerfile (init)
<...>
STEP 1/4: FROM registry.redhat.io/openshift4/network-tools-rhel8:latest
STEP 2/4: RUN yum install -y NetworkManager && yum clean all
<...>
No match for argument: NetworkManager
Error: Unable to find a match: NetworkManager
error: build error: error building at STEP "RUN yum install -y NetworkManager && yum clean all": error while running runtime: exit status 1
```

The other images, such as `ubi7/8/9` or `centos 8/9` are all on the same page. 

Next tried to create a pod with `registry.redhat.io/openshift4/network-tools-rhel8` image but it doesn't have NetworkManager in this image.

```yaml
oc create -f -<<EOF
apiVersion: v1
kind: Pod
metadata:
  name: dhcp-monitor-nw-tools-rhel8-2
  namespace: openshift-bcgov-nagios
spec:
  containers:
  - name: dhcpmonitor
    image: registry.redhat.io/openshift4/network-tools-rhel8:latest
    securityContext:
      privileged: true
    command:
      - "/bin/sh"
      - "-c"
      - "trap : TERM INT; sleep infinity & wait"
    volumeMounts:
    - name: dhcpmonitor
      mountPath: /var/run/dbus
  volumes:
  - name: dhcpmonitor
    hostPath:
      path: /var/run/dbus
      type: DirectoryOrCreate
  serviceAccount: dhcpmonitor
  serviceAccountName: dhcpmonitor
```

This created pod but it doesn't have NetworkManager nor let install NetworkManager.

```cmd
KLAB/openshift-bcgov-nagios ~/dhcp-monitor $ oc get pod
NAME                                        READY   STATUS      RESTARTS   AGE
dhcp-monitor-centos7                        1/1     Running     0          5h1m
dhcp-monitor-nmcli-nw-tools-rhel8-2-build   0/1     Error       0          4h51m
<...>

// run nmcli - not found.
KLAB/openshift-bcgov-nagios ~/dhcp-monitor $ oc rsh dhcp-monitor-nw-tools-rhel8-2
sh-4.4# nmcli -h
sh: nmcli: command not found

// try to install NetworkManager - failed, same as build log. 
sh-4.4# yum install NetworkManager
<...>
Last metadata expiration check: 0:33:56 ago on Fri Jul 21 23:02:52 2023.
No match for argument: NetworkManager
Error: Unable to find a match: NetworkManager
sh-4.4#
```

On the other hand, centos:7 works. 

BuildConfig:

```yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: dhcp-monitor-nmcli
    namespace: openshift-bcgov-nagios # your namespace
spec:
  runPolicy: Serial
  source:
    dockerfile: |
      FROM centos:7
      # Install nmcli
      RUN yum install -y NetworkManager && yum clean all

  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
  output:
    to:
      kind: ImageStreamTag
      name: "dhcp-monitor-nmcli:latest"
```

Build was suucessfull so that `ImageStream` got tag:

```
KLAB/openshift-bcgov-nagios ~/dhcp-monitor $ oc get is
NAME                                IMAGE REPOSITORY                                                                                     TAGS     UPDATED
dhcp-monitor-nmcli                  image-registry.apps.klab.devops.gov.bc.ca/openshift-bcgov-nagios/dhcp-monitor-nmcli                  latest   29 hours ago
<...>
``` 

And pod can be cretated and run `nmcli`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dhcp-monitor-centos7
  namespace: openshift-bcgov-nagios
spec:
  containers:
  - name: dhcp-monitor-centos7
    image: image-registry.apps.klab.devops.gov.bc.ca/openshift-bcgov-nagios/dhcp-monitor-nmcli:latest
    securityContext:
      privileged: true
    command:
      - "/bin/sh"
      - "-c"
      - "trap : TERM INT; sleep infinity & wait"
    # Mount dbus volume from the host
    volumeMounts:
    - name: dhcpmonitor
      mountPath: /var/run/dbus
  volumes:
  - name: dhcpmonitor
    hostPath:
      path: /var/run/dbus
      type: DirectoryOrCreate
  serviceAccount: dhcpmonitor
  serviceAccountName: dhcpmonitor
```

Command test: 

```cmd
// pod running
KLAB/openshift-bcgov-nagios ~/dhcp-monitor $ oc get pods
NAME                                        READY   STATUS      RESTARTS   AGE
dhcp-monitor-centos7                        1/1     Running     0          5h12m
<...>

//login to the pod
KLAB/openshift-bcgov-nagios ~/dhcp-monitor $ oc rsh dhcp-monitor-centos7-2

//nmcli existed.
sh-4.2# nmcli -h
Usage: nmcli [OPTIONS] OBJECT { COMMAND | help }

//shell script test
sh-4.2# LIMIT=$(date --date='+5 hour' '+%s');
sh-4.2# for T in $(nmcli -f dhcp4.option dev show | sed -n -e '/expiry/s/.*expiry = //p');
> do
>   if (( "$T" < "$LIMIT" )); then
> echo "DHCP lease expiring in less than 5 hours";
> exit 1;
>   else
> echo "DHCP is not expiring.";
>   fi;
> done
DHCP is not expiring.
<...>

// variables are properly set
sh-4.2# echo $LIMIT
1690001478
sh-4.2# echo $T
1690006746
```

**Comment by tmorik** [comment]
Next step will be `DeamonSet` (or CronJob with parallelism -- loos like cj can run on each host using this and much secure as this pod privileged, i think  ) and Nagios integration.

**Comment by tmorik** [comment]
Memo: To run a DS or CronJob's pod in master or infra, need to add below to the namespace obj:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nagios
  namespace: openshift-bcgov-nagios
  openshift.io/node-selector: ""                   // <-- Add this !
<...>
```

Now,  pods are running on the control-planes.

```
dhcpcheck-cj-manual-2fsj8                   0/1     Completed   0          5s      <IP Addr>     mcs-klab-infra-02.dmz    <none>           <none>
dhcpcheck-cj-manual-4ffgp                   0/1     Completed   0          5s      <IP Addr>     mcs-klab-app-01.dmz      <none>           <none>
dhcpcheck-cj-manual-gpqn6                   0/1     Completed   0          5s      <IP Addr>     mcs-klab-master-03.dmz   <none>           <none>
dhcpcheck-cj-manual-mxkvh                   0/1     Completed   0          5s      <IP Addr>     mcs-klab-master-01.dmz   <none>           <none>
dhcpcheck-cj-manual-njkb4                   0/1     Completed   0          5s      <IP Addr>      mcs-klab-infra-03.dmz    <none>           <none>
dhcpcheck-cj-manual-rx9zc                   0/1     Completed   0          5s      <IP Addr>    mcs-klab-app-02.dmz      <none>           <none>
dhcpcheck-cj-manual-t4kbt                   0/1     Completed   0          5s      <IP Addr>     mcs-klab-master-02.dmz   <none>           <none>
dhcpcheck-cj-manual-wj5cg                   0/1     Completed   0          5s      <IP Addr>    mcs-klab-app-04.dmz      <none>           <none>
dhcpcheck-cj-manual-zmh82                   0/1     Completed   0          5s      <IP Addr>    mcs-klab-app-03.dmz      <none>           <none>
dhcpcheck-cj-manual-zx6gj                   0/1     Completed   0          5s      <IP Addr>      mcs-klab-infra-01.dmz    <none>           <none>
dhcpcheck-ds-b29wv                          1/1     Running     0          17m     <IP Addr>    mcs-klab-master-02.dmz   <none>           <none>
dhcpcheck-ds-chmkb                          1/1     Running     0          17m     <IP Addr>    mcs-klab-master-03.dmz   <none>           <none>
dhcpcheck-ds-hmndc                          1/1     Running     0          17m     <IP Addr>   mcs-klab-app-03.dmz      <none>           <none>
dhcpcheck-ds-lv6sp                          1/1     Running     0          17m     <IP Addr>    mcs-klab-infra-01.dmz    <none>           <none>
dhcpcheck-ds-plrwr                          1/1     Running     0          17m     <IP Addr>   mcs-klab-app-04.dmz      <none>           <none>
dhcpcheck-ds-plxl9                          1/1     Running     0          17m     <IP Addr>   mcs-klab-app-02.dmz      <none>           <none>
dhcpcheck-ds-rdtvq                          1/1     Running     0          17m     <IP Addr>   mcs-klab-infra-03.dmz    <none>           <none>
dhcpcheck-ds-sztw9                          1/1     Running     0          17m     <IP Addr>   mcs-klab-app-01.dmz      <none>           <none>
dhcpcheck-ds-xlrgt                          1/1     Running     0          17m     <IP Addr>    mcs-klab-master-01.dmz   <none>           <none>
dhcpcheck-ds-zh5n9                          1/1     Running     0          17m     <IP Addr>    mcs-klab-infra-02.dmz    <none>           <none>
```
