### ISSUE TITLE
Install Terminal-Operator on PROD clusters

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3165]
**Describe the issue**
Adjust the relevant platform-gitops-gen files to install the Web terminal operator in the PROD clusters.

**Additional context**
https://access.redhat.com/support/cases/#/case/03310194 documents the required NetPols to make this work.

**How does this benefit the users of our platform?**
Allows quick and easy access to the Openshift cli.

**Definition of done**
- [x] Install the Terminal Operator via CCM in the PROD clusters
- [x] Demo at next Community Meetup
- [x] Add the required Netpol to namespaces
  - [x] @IanKWatts will modify the provisioner and deploy the netpols in LAB clusters user namespaces. (create a ZenHub ticket.)
  - [x] MCS will review and make sure Terminal Operator is working on user namespaces.
  - [x] Documentations
  - [x] Set a date for deploying to PROD clusters

**Comment by tmorik** [comment]
Had a meeting with Tim and confirmed netpols `allow-from-web-terminal` and `allow-from-console` that needs to be in each namespaces. 

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-web-terminal
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-operators
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-console
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: console
  podSelector: {}
  policyTypes:
    - Ingress
```

Once these netpols are deployed in the test namespace, test user (we used `advsol-mcs-test`) can launch up WebTerminal in its Web Console. 

### CLAB Web Console - advsol-mcs-test

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/0869243d-6621-4a3a-9fd4-9c19f2ee2d49)

**Comment by tmorik** [comment]
If you want to deploy these web terminals in all namespaces, we can ask Ian to apply these two network policies, or write a memo to the government documentation site or Stack Overflow site so that users can set them up themselves.

**Comment by tmorik** [comment]
Next steps:

- Post a terminal operator info in # how-to channel : https://chat.developer.gov.bc.ca/channel/devops-how-to?msg=Nqb9W4dgGyWsZpRnu
- Have a meeting with sec team to make sure networkpolicies for the Terminal Operator.

**Comment by StevenBarre** [comment]
Posted on RC to see if there was interest. The response was good.

![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/b849f505-4932-4d9f-971b-26cc65d8f078)

**Comment by tmorik** [comment]
Had the meeting with Nick and Avneet. Got their positive feedbacks. They will review the netpols and let us know.

**Comment by NickCorcoran** [comment]
Netpols reviewed.  Capabilities understood.  Operator is GA (no longer preview).  
Provides a good user experience for developers.  Similar to AWS CloudShell capability.  
Please proceed with implementation.

**Comment by tmorik** [comment]
Thank you Nick, I will prepare CCM PR for these netpols.

**Comment by tmorik** [comment]
Hat the meeting with Ian. Next steps will be...

- [ ] Ian will modify the provisioner and deploy the netpols in LAB clusters user namespaces. (create a ZenHub ticket.) 
- [ ] MCS will review and make sure Terminal Operator is working on user namespaces.
- [ ] Documentations
- [ ] Set a date to deploy to PROD clusters.

**Comment by tmorik** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/657/files

**Comment by IanKWatts** [comment]
Provisioner has been updated to include the new rules in the default network policy.
I will test the updated "full sync" workflow and apply the change to all lab projects, verify, then apply to prod.
The only catch is that this will also update the default admin rolebinding.  Like this change, the provisioner has been updated, but we have not yet done a full sync to update all namespaces.  I'll check with Nick about that.

**Comment by IanKWatts** [comment]
@tmorik and @StevenBarre Before I apply the network policy update to KLAB2, I have a question about the existing default.  It includes the following block with I do not have in my template.  Should this be added to the template?
```
      to:
      - ipBlock:
          cidr: 10.99.1.66/32
      - ipBlock:
          cidr: 10.99.1.67/32
      - ipBlock:
          cidr: 10.99.1.68/32
```
For example, see at the bottom of this NetworkPolicy: 
https://console.apps.klab2.devops.gov.bc.ca/k8s/ns/c4b9c2-dev/networkpolicies/platform-services-controlled-deny-by-default/yaml
