### ISSUE TITLE
CCM - Update Keda subscription resource to increase operator RAM limit

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3391]
**Describe the issue**
A recent CCM push installed Keda in all clusters. As per normal now for some operators , this operator needs significantly higher memory limits for the initial operator than the default grants. Experimentation was done via doubling the memory limit until a value was reached that ensured stability for SILVER.

This manual change in SILVER will need to be codified and merged into the main CCM repo.

**Additional context**
The following will need to be added to the `spec` section of the Keda subscription resource.
```
  config:
    resources:
      limits:
        cpu: 500m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 100Mi
```

**How does this benefit the users of our platform?**
Ensure stability of operators in play, thus ensuring the services rendered are also stable.

**Definition of done**
- [x] Create new PR with above additions to the main CCM repo.
- [x] Obtain approval and merge PR.
- [x] Confirm change works by merging one or more LAB CCM repos.
