### ISSUE TITLE
Install "OpenShift API for Data Protection” (OADP) Operator in KLAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#3624]
The Integration team in AG needs to have the "OpenShift API for Data Protection” (OADP) Operator installed in KLAB to test.

The contact there is Jennifer Dowd. More context: "we need this operator to the “7c91c0-dev” namespace. (Relevant location: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/7c91c0-dev/operators.coreos.com~v1alpha1~ClusterServiceVersion). This is for developing a configuration to backup and restore Nextcloud OpenShift cluster resources (yaml files), internal images and persistent volume data. (FAQ for the OADP here https://access.redhat.com/articles/5456281)"

**Comment by StevenBarre** [comment]
Installed in KLAB

Appears that this is only usable by cluster admins, and is not designed for multi-tenant use. The operator is looking for Backup objects only in its own namespace.

Set up a Minio server to use as a S3 endpoint to store backups. Set up a test DataProtectionApplication with mino as the storage point. Set up a test backup object and confirmed it backed up the test namespace.

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup
namespace: openshift-adp
spec:
  defaultVolumesToRestic: true
  includedNamespaces:
    - stevenbarre-test
  storageLocation: dpa-test-1
```
