### ISSUE TITLE
SDN - Request Firewall rule(s) for allowing access to Nagios Test Pods in KLAB2/EMERALD clusters

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3795]
**Describe the issue**
Two Nagios Active checks are failing for both KLAB2 and EMERALD and is due to a lack of firewall rules allowing access to VIPs involved with Nagios test pods.

We might just open up access to all possible AVI VIPs in the end so that we're not limited on future monitoring checks.

**Blocked By**
Waiting for internal firewall request to be created/submitted/approved/implemented.

**Additional context**
Current Nagios Active checks failing:
* Speed_Test_443
* Speed_Test_80

**How does this benefit the users of our platform?**
These specific Nagios checks reflect quality of network speed when accessing applications in KLAB2/EMERALD via http/https.

**Definition of done**
- [x] Identify if only current VIPs for Nagios test pods will be opened up or if we will open up all VIP pools for the clusters.
- [x] Submit firewall request to satisfy port 80 request.
- [x] Confirm resolution by making sure the two Speed_Test checks are cleared for both clusters.

**Comment by wmhutchison** [comment]
Firewall request not yet submitted. Was hoping to find an example of an existing request since we're able to hit the console URLs in Nagios.

**Comment by wmhutchison** [comment]
Increased priority for this ticket will be provided for the Sprint starting May 25th.

**Comment by wmhutchison** [comment]
With the demands of OCP 4.12 and associated NSX patching now out of this way, can put more cycles into this.

**Comment by wmhutchison** [comment]
Enabling one of these tests for KLAB2 briefly. Should be fine since the manually-configured test at the time was for the Nagios nginx test pod.

**Comment by wmhutchison** [comment]
current route definition for this check in NSX/AVI renders differently than for regular Openshift. Regular Openshift allows the single route to use both http and https interchangeably while for AVI/NSX, attempts to hit http:// return a redirect to use https instead.

Will see if this can be solved in a simple fashion. Otherwise wlll refactor these tests to provide an explicit secure and insecure route so that this issue won't be encountered again.

**Comment by wmhutchison** [comment]
spoke too soon regarding not needing firewall rules. Check from NAgios involving http access do not work, while https does. Weird thing is that failures aren't showing up in firewall logs I have access to or in VRLI as a block, so something else is going on here.

**Comment by wmhutchison** [comment]
Internal firewall request now submitted, moving to Blocked until fulfilled.

**Comment by wmhutchison** [comment]
firewall request was fulfilled, both Speed_test checks are now working. Will need to now back-track to see what needs to be modified in the repo to make this manual adjustment permanent across all clusters.

**Comment by wmhutchison** [comment]
To true up this specific ticket, the following changes need to be made.

1. Create new route for `nginx-insecure-openshift-bcgov-nagios.apps.<cluster>.devops.gov.bc.ca` so that we can make the `Speed_Test_80` test work correctly on KLAB2/EMERALD. Sample YAML below.
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx
  name: nginx-insecure
  namespace: openshift-bcgov-nagios
spec:
  host: nginx-insecure-openshift-bcgov-nagios.apps.klab2.devops.gov.bc.ca
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None
```
2. Update the `Speed_Test_80` Nagios check to use the insecure route created above. No changes need to be made to the `Speed_Test_443' check.
