### ISSUE TITLE
Increase vm.max_map_count for ElasticSearch

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#402]
https://trello.com/c/Y5yxLOdL/100-increase-vmmaxmapcount-for-elasticsearch

Appears it is safe to do this https://access.redhat.com/solutions/99913

Karim would like to run ElasticSearch and it wont start without this setting.
https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

OCP Playbooks already do this for the infra nodes

```
- name: Update vm.max_map_count for ES 5.x
  hosts: oo_elasticsearch_nodes
  gather_facts: false
  tasks:
  - when: openshift_logging_install_logging | default(false) | bool
    block:
    - name: Checking vm max_map_count value
      command:
        cat /proc/sys/vm/max_map_count
      register: _vm_max_map_count

    - name: Updating vm.max_map_count value
      sysctl:
        name: vm.max_map_count
        value: 262144
        sysctl_file: "/etc/sysctl.d/99-elasticsearch.conf"
        reload: yes
      when:
      - _vm_max_map_count.stdout | default(0) | int < 262144 | int
```
