### ISSUE TITLE
Install Confluent Kafka operator in KLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4621]
**Describe the issue**
Spencer would like to test out https://docs.confluent.io/operator/current/overview.html in a lab cluster

**What is the Value/Impact?**
> AMQ doesn’t quite meet all our requirements, whereas the Confluent Kafka provides the needed features and support for our project.

**What is the plan? How will this get completed?**
Install in KLAB. Ask AG team that uses AMQ to confirm no negative impacts from the double install. Have Spencer test and report back.

**Identify any dependencies**
Need feedback from AG and from Spencer

**Definition of done**
- Confluent Kafka operator installed
- Determination of a plan to deploy to other clusters and impact analysis

**Comment by StevenBarre** [comment]
Created a namespace
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: node-role.kubernetes.io/infra=
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-confluent
```

https://docs.confluent.io/operator/current/co-deploy-cfk.html#deploy-co-using-the-download-bundle

```
helm upgrade --install confluent-operator \
  ./confluent-for-kubernetes \
  --set namespaced=false \
  --set podSecurity.enabled=false \
  --set resources.limits.memory=2Gi \
  --namespace openshift-confluent
```

Needs the extra memory or else it OOMKills. Namespaced False so all namespaces can use it. Disable pod security due to being on OCP.

Operator pod is running now. Asked Spencer to try installing the Platform in their namespace.

**Comment by StevenBarre** [comment]
Adding a ClusterRole

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  labels:
    app: confluent-for-kubernetes
  name: confluent-admin-tenant
rules:
- apiGroups:
  - platform.confluent.io
  resources:
  - '*'
  verbs:
  - '*'
```
