### ISSUE TITLE
AG ISB OpenShift logging - investigate and test in a LAB

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#4660]
**Describe the issue**
Investigate the possibility of using ClusterForwarders to send logs for just some select namespaces to a Splunk endpoint. 

**Additional context**
https://docs.openshift.com/container-platform/4.13/logging/log_collection_forwarding/configuring-log-forwarding.html#cluster-logging-collector-log-forward-logs-from-application-pods_configuring-log-forwarding

Also need to check if this could cause increased alerts for PlatOps from the logging system if Splunk is not ingesting fast enough.

**How does this benefit the users of our platform?**
Simplifies log exporting for the AG team

**Definition of done**
Tested in a LAB cluster with a clear plan on how to implement in prod, or a decision that this can't be supported.

**Comment by StevenBarre** [comment]
Blocked on a firewall update from AG to allow KLAB to connect to the Splunk instance.

Will then set up forwarding for fbca9a-* namespace

**Comment by StevenBarre** [comment]
This seems to be working, but has spun up a second DaemonSet just for this. Need to dig more to see if I can get the existing collector to do this.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ag-isb
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-logging-openshift-logging-ag-isb-splunk-metadata-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metadata-reader
subjects:
- kind: ServiceAccount
  name: ag-isb
  namespace: openshift-logging
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: ag-isb-splunk
  namespace: openshift-logging
spec:
  inputs:
  - application:
      namespaces:
      - fbca9a-tools
      - fbca9a-dev
      - fbca9a-test
      - fbca9a-prod
    name: ag-isb-splunk
  outputs:
  - name: ag-isb-splunk
    secret:
      name: ag-isb-splunk
    type: splunk
    url: https://AG-SPLUNK-HOST:8088
  pipelines:
  - inputRefs:
    - ag-isb-splunk
    name: ag-isb-splunk
    outputRefs:
    - ag-isb-splunk
  serviceAccountName: ag-isb
```
