### ISSUE TITLE
Install Data Science in Silver

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4739]
**Describe the issue**
See [previous ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/3993) for implementation details.

We have gotten some licenses for Data Science and want to install it in Silver. Red Hat will be doing a demo on Apr 23rd so we should get this installed before then.

**What is the Value/Impact?**
Make Data Science Operator available to early adopter teams

**What is the plan? How will this get completed?**
Install ODS in Silver
Apply custom hacks needed to get the false alerts to stop
Apply quota to ods notebook namespace to prevent over-use
Add annotations to test users tools and dev namespaces to allow them to leverage ODS

**Identify any dependencies**
None

**Definition of done**
ODS installed in Silver and enabled for testing

**Comment by wmhutchison** [comment]
Will attempt to get a viable CCM PR into the upcoming CCM release, but given everything else going on of higher priority, it's not a certainty. Will likely bend the rules in terms of creating new release/RFCs to give us some wiggle room to make this happen, but if it doesn't, so be it.

**Comment by wmhutchison** [comment]
Checked older tickets on this matter. Thought it was installed via CCM, but not so, was installed manually via OperatorHub instead. Thus no older PR I can quickly whip up and squeeze into next week's CCM release.

Will ask Steven when he's back if he wants this CCM-enabled or not. If so, then will look into this but will most certainly need additional R & D time in a LAB cluster to figure it all out.

**Comment by StevenBarre** [comment]
Attempted to install but the operator pod is crashlooping. Opened a RH case https://access.redhat.com/support/cases/#/case/03795149

**Comment by StevenBarre** [comment]
To enable user namespaces label them with `opendatahub.io/dashboard: 'true'`

Old hacks for alerting/monitoring no longer needed as fixed in 2.8

**Comment by StevenBarre** [comment]
Turns out the `rhods-admins` group is too powerful, have removed all users from it.

Reading the docs, I think we may also want to disable the Jupyter app? Force teams to run a workbench in their own namespaces? https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_cloud_service/1/html/managing_resources/managing-applications-that-show-in-the-dashboard#hiding-the-default-jupyter-application_dashboard

**Comment by StevenBarre** [comment]
Trying out the "hello world" app https://docs.redhat.com/en/documentation/red_hat_openshift_ai_cloud_service/1/html/openshift_ai_tutorial_-_fraud_detection_example/index

Needed to create a netpol for the model server

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: advsol-modelmesh
  namespace: 21001b-dev
spec:
  podSelector:
    matchLabels:
      modelmesh-service: modelmesh-serving
  ingress:
    - ports:
        - protocol: TCP
          port: 8033
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: redhat-ods-applications
  policyTypes:
    - Ingress
```
