### ISSUE TITLE
Install Connectivity Link in a LAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5890]
**Describe the issue**
Install Connectivity Link and Service Mesh into a lab cluster for testing and understanding how it works

**What is the Value/Impact?**
Allow SSO to test this tool

**What is the plan? How will this get completed?**
https://developers.redhat.com/products/red-hat-connectivity-link/quick-setup

**Identify any dependencies**
May need eval licenses from RH

**Impact of work**
- [ ] Does training material need to be updated? Not currently, but would if deployed to prod
- [ ] Does documentation need to be updated? Not currently, but would if deployed to prod
- [ ] Do we need to make an announcement? Not currently, but would if deployed to prod
- [ ] Does this change our supported services responsibilities? Not currently, but would if deployed to prod

**Definition of done**
Installed in a lab cluster

**Comment by StevenBarre** [comment]
Got the eval licenses

**Comment by StevenBarre** [comment]
Used the F5 to expose the Gateway by adding an annotating to the generated service to specify an IP.
Completed the quick-setup guide
Opened a case about RBAC for non-cluster admins

**Comment by StevenBarre** [comment]
Some more links to read
https://www.solutionpatterns.io/soln-pattern-connectivity-link/solution-pattern/index.html
https://docs.kuadrant.io/1.2.x/authorino/docs/features/#common-feature-conditions-when
https://github.com/Kuadrant/architecture/blob/main/rfcs/0002-well-known-attributes.md

**Comment by StevenBarre** [comment]
https://access.redhat.com/support/cases/#/case/04196990 RH says they don't have any docs on RBAC. Created this myself which seems to work.

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhcl
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - gateway.networking.k8s.io
      - kuadrant.io
      - limitador.kuadrant.io
    resources:
      - '*'
```
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhcl
  namespace: bb3153-dev
rules:
  - verbs:
      - create
      - delete
      - update
      - patch
    apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
  - verbs:
      - create
      - delete
      - update
      - patch
    apiGroups:
      - kuadrant.io
    resources:
      - authpolicies
      - dnspolicies
      - kuadrants
      - ratelimitpolicies
      - tlspolicies
  - verbs:
      - create
      - delete
      - update
      - patch
    apiGroups:
      - limitador.kuadrant.io
    resources:
      - limitadors
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - gateway.networking.k8s.io
      - kuadrant.io
      - limitador.kuadrant.io
    resources:
      - '*'
```
