### ISSUE TITLE
Deploy Sysdig Operator to KLAB and ARO and test

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#823]
**Describe the issue**
Deploy Sysdig Operator to KLAB and ARO. In each cluster, a team must be able to successfully create the custom resource for their project set and should be able to see their resources within the Sysdig dashboard. 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Deployed & tested in ARO Pathfinder Cluster
- [x] Deployed & tested in KLAB cluster

@stewartshea  will handle the manifest creation and PR's.
@stewartshea will handle approvals for ARO and can test in KLAB.

**Comment by stewartshea** [comment]
This has been deployed and managed by ArgoCD inside of the pathfinder cluster. A couple of items to consider before it goes into KLAB: 
- [ ] Secret with API token is required to run the playbook - this will need to be created and manged with kubeseal possibly? Vault would be more ideal. 
- [ ] The image is still currently built in the pathfinder cluster and this should be moved to Artifactory.

**Comment by stewartshea** [comment]
This has been deployed in KLAB. Currently testing and troubleshooting a connection error when trying to remove the team. 

```
status:
  conditions:
    - lastTransitionTime: '2021-01-18T19:02:06Z'
      message: Running reconciliation
      reason: Running
      status: 'False'
      type: Running
    - ansibleResult:
        changed: 0
        completion: '2021-01-18T19:04:12.117863'
        failures: 1
        ok: 4
        skipped: 0
      lastTransitionTime: '2021-01-18T19:04:12Z'
      message: >-
        Status code was -1 and not [200]: Request failed: <urlopen error timed
        out>
      reason: Failed
      status: 'True'
      type: Failure
```
