### ISSUE TITLE
Create starter policy for namespaces to require a security first posture

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#914]
## Story

As Platform Services, we require teams on OCP4 to adopt a security first approach to application management. 

## Description 

With Aporeto we had a deny-by-default rule in place. Teams, as they saw fit, were able to implement policy within their namespace to be very restrictive (control specific pod communication) or to be wide open (all pods can talk to all other pods). With the migration to NetworkPolicy (NP) we need similar policy in place to wall off a namespace form others as well as deny all internal traffic. Then teams, as they see fit, can open up their namespace.

## Done When

As each namespace is cut over from Aporeto to KNP we need one default policy rolled out that covers all pods within a namespace.

**Comment by jleach** [comment]
This base policy seems to work quite well.

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-by-default
  labels:
    owned-by: platform-services
spec:
  podSelector: {}
  ingress: []
```
