### ISSUE TITLE
Install Vertical Pod Autoscaler in KLAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#992]
As a Platform Services team member I want to evaluate a new resource tuning tool [Vertical Pod Autoscaler](https://docs.openshift.com/container-platform/4.7/nodes/pods/nodes-pods-vertical-autoscaler.html) that is available in tech preview in OCP 4.5 and is planned for GA in OCP 4.8.

The VPA gives cluster administrators, product owners or project administrators recommendations around CPU and memory for requests and limits based on the running profile of their application.

Once configured for an application, the VPA will start to report containerRecommendations for their Deployment(s) that includes a lower bound, upper bound and target for CPU and Memory.

Using those recommendations, the VPA can take action in 3 ways:
1) Recreate - Kill and update the pods using the recommendations
2) Initial - Use the recommendations the next time the pod starts / restarts on its own
3) Off - Just tell us the recommendations and let teams make their own updates

In most cases, off is the best choice because it gives teams the necessary insights without unplanned changes to their running applications. Also, in all 3 scenarios, teams would still need to commit those changes into their git repo to make them permanent.

The challenges boil down to teams needing to tell the VPA to watch their application and the teams then needing to act on any recommendations (if Off). To combat that, this could become a best / enforced practice. Alternatively, it could be teams can leverage based on known bad configurations surfaced through cost data.

DoD:
- [x] Vertical Pod Autoscaler operator installed in KLAB in the "off" mode e.g. produce recommendations report for apps but do not enforce the recommendations.

**Comment by mitovskaol** [comment]
@juhewitt  ^^^

**Comment by StevenBarre** [comment]
PR for CCM https://github.com/bcgov-c/platform-gitops-gen/pull/105

Installed manually in KLAB to get some of the data to make CCM manifests.

Created a VPA for Sysdig Agent

```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-worker
  namespace: openshift-bcgov-sysdig-agent
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       DaemonSet
    name:       sysdig-agent-worker
  updatePolicy:
    updateMode: "Off"
```

Got back these recommendations

```yaml
  status:
    conditions:
    - lastTransitionTime: "2021-03-03T04:05:24Z"
      status: "True"
      type: RecommendationProvided
    recommendation:
      containerRecommendations:
      - containerName: sysdig-agent
        lowerBound:
          cpu: 234m
          memory: "282451377"
        target:
          cpu: 296m
          memory: "511772986"
        uncappedTarget:
          cpu: 296m
          memory: "511772986"
        upperBound:
          cpu: 7907m
          memory: "13671649768"
```
